### ISSUE TITLE
Exception thrown on empty parameters file

### ISSUE THREAD

**Issue by stuartellis** [stuartellis/button#1]
Traceback:

```Error parsing parameter '--parameters': Expected: '=', received: 'EOF' for input:

^
Traceback (most recent call last):
  File "./button.py", line 278, in <module>
    main(CF_CMD_MAPPINGS, VERSION)
  File "./button.py", line 77, in main
    run_cmds(cmd_list, config)
  File "./button.py", line 271, in run_cmds
    raise Exception(result)
Exception: 255```

**Comment by stuartellis** [comment]
The root cause was the use of a dummy parameters file: 0.5.0 required a parameters file, even if the CF template did not use any input parameters.

The parameters file is now optional. Debugging output will now explicitly show whether or not a  parameters file is being used.
